In [83]:
import torch

x = torch.load('../experiments/rgfn_seh_proxy_test/2024-11-18_12-23-19/train/checkpoints/initial.pt')
x

{'model': OrderedDict([('logZ',
               tensor([2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438,
                       2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438])),
              ('forward_policy.gnn.x2h.0.weight',
               tensor([[-0.0551,  0.0920, -0.0333,  ..., -0.1085, -0.0812, -0.0076],
                       [ 0.1126, -0.0829, -0.0545,  ..., -0.1049,  0.0788, -0.0982],
                       [ 0.0394, -0.0467, -0.0963,  ..., -0.0831, -0.0709,  0.1058],
                       ...,
                       [ 0.0212,  0.0882, -0.0607,  ..., -0.0721,  0.1167,  0.0386],
                       [ 0.0008, -0.0228, -0.0439,  ...,  0.0324,  0.0553,  0.0002],
                       [-0.0682, -0.0804,  0.0621,  ..., -0.0021,  0.0768,  0.0189]])),
              ('forward_policy.gnn.x2h.0.bias',
               tensor([-0.0352, -0.0804, -0.0269,  0.0641, -0.0931,  0.1135,  0.0315, -0.1176,
                       -0.0139,  0.0588,  0.0904, -0.0122

In [84]:
y = torch.load('../experiments/rgfn_seh_proxy_test/2024-11-18_12-22-58/train/checkpoints/initial.pt')
y

{'model': OrderedDict([('logZ',
               tensor([2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438,
                       2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438, 2.3438])),
              ('forward_policy.gnn.x2h.0.weight',
               tensor([[-0.0551,  0.0920, -0.0333,  ..., -0.1085, -0.0812, -0.0076],
                       [ 0.1126, -0.0829, -0.0545,  ..., -0.1049,  0.0788, -0.0982],
                       [ 0.0394, -0.0467, -0.0963,  ..., -0.0831, -0.0709,  0.1058],
                       ...,
                       [ 0.0212,  0.0882, -0.0607,  ..., -0.0721,  0.1167,  0.0386],
                       [ 0.0008, -0.0228, -0.0439,  ...,  0.0324,  0.0553,  0.0002],
                       [-0.0682, -0.0804,  0.0621,  ..., -0.0021,  0.0768,  0.0189]])),
              ('forward_policy.gnn.x2h.0.bias',
               tensor([-0.0352, -0.0804, -0.0269,  0.0641, -0.0931,  0.1135,  0.0315, -0.1176,
                       -0.0139,  0.0588,  0.0904, -0.0122

In [85]:
for key in x['model']:
    assert torch.allclose(x['model'][key], y['model'][key])

In [86]:
x = torch.load('../container_1.pt')
y = torch.load('../container_2.pt')


In [99]:
for traj_idx, (states_1, states_2) in enumerate(zip(x.forward_trajectories._actions_list, y.forward_trajectories._actions_list)):
    for s_idx, (s1, s2) in enumerate(zip(states_1, states_2)):
        if s1 != s2:
            print(f'{s1} != {s2}, {traj_idx}, {s_idx}')
# actions_1 = [actions[-5] for actions in x.forward_trajectories._actions_list]
# actions_2 = [actions[-5] for actions in y.forward_trajectories._actions_list]
# actions_1 == actions_2

AC(F(267), R([C:2]-[Oh:3].[Ch2:1]-[Br] >> [Ch2:1]-[O:3]-[C:2]), (F(266),), O=C(O)COCC(=O)O) != AC(F(267), R([C:2]-[Oh:3].[Ch2:1]-[Br] >> [Ch2:1]-[O:3]-[C:2]), (F(266),), O=C(O)COC(=O)CO), 2, 3
AC(O=C(O)COCC(=O)O, R([#6:15][C:14](=[O])-[Oh].[c:3]1[c:4][c:5][c:6]([C:11][C:12][Nh2:13])[c:7][c:8]1 >> [c:3]1[c:4][c:5]2[c:6]([C:11][C:12][N:13]=[C:14]2-[#6:15])[c:7][c:8]1), (F(218),), O=C(O)COCC1=N[C@@H](C(=O)O)Cc2ccc(O)cc21) != AC(O=C(O)COC(=O)CO, R([#6:15][C:14](=[O])-[Oh].[c:3]1[c:4][c:5][c:6]([C:11][C:12][Nh2:13])[c:7][c:8]1 >> [c:3]1[c:4][c:5]2[c:6]([C:11][C:12][N:13]=[C:14]2-[#6:15])[c:7][c:8]1), (F(218),), O=C(CO)OCC1=N[C@@H](C(=O)O)Cc2ccc(O)cc21), 2, 6
AC(O=C(O)COCC1=N[C@@H](C(=O)O)Cc2ccc(O)cc21, R([C:3](=[O:4])-[Oh].[#6&!$(C=[O]):1]-[Oh:2] >> [C:3](=[O:4])-[O:2]-[#6&!$(C=[O]):1]), (F(194),), NCc1cccc(OC(=O)COCC2=N[C@@H](C(=O)O)Cc3ccc(O)cc32)c1) != AC(O=C(CO)OCC1=N[C@@H](C(=O)O)Cc2ccc(O)cc21, R([C:3](=[O:4])-[Oh].[#6&!$(C=[O]):1]-[Oh:2] >> [C:3](=[O:4])-[O:2]-[#6&!$(C=[O]):1]), (F(194

In [94]:
for a1, a2 in zip(actions_1, actions_2):
    if a1 != a2:
        print(f'{a1} != {a2}')

AC(NCc1cccc(OC(=O)COCC2=N[C@@H](C(=O)O)Cc3ccc(O)cc32)c1, R([C:1](=[O])[Oh].[Nh2:2]-[#6&!$(C=[O,N]):3] >> [C:1]-[Nh:2]-[#6&!$(C=[O,N]):3]), (F(215),), NCc1cccc(OC(=O)COCC2=N[C@@H](CN[C@H](CS)C(=O)O)Cc3ccc(O)cc32)c1) != AC(NCc1cccc(OC(=O)[C@H]2Cc3ccc(O)cc3C(COC(=O)CO)=N2)c1, R([Nh2:2]-[#6&!$(C=[O,N]):3].[C:1](=[O])[Oh] >> [C:1]-[Nh:2]-[#6&!$(C=[O,N]):3]), (F(287),), O=C(CO)OCC1=N[C@@H](C(=O)Oc2cccc(CNCc3cccc(F)n3)c2)Cc2ccc(O)cc21)
AC(F(57), R([#6:6]-[Ch:1]=[O].[Nh2:5]-[c;r6:4][c;r6:3]-[Nh2:2] >> [n:5]1[c:4][c:3][nH:2][c:1](-[#6:6])1), (F(152),), COC(=O)c1ccc(-c2nc3cc(C#N)ccc3[nH]2)cc1) != AC(F(57), R([#6:6]-[Ch:1]=[O].[Nh2:5]-[c;r6:4][c;r6:3]-[Nh2:2] >> [n:5]1[c:4][c:3][nH:2][c:1](-[#6:6])1), (F(152),), COC(=O)c1ccc(-c2nc3ccc(C#N)cc3[nH]2)cc1)
AC(O=C(COC(=O)[C@H]1CCCN(C(=O)c2ccc(N[C@@H](CS)C(=O)O)c(C(F)(F)F)c2)C1)c1ccc(O)c(O)c1, R([#6:6]-[C:1](=[O])-[Oh].[Nh2:5]-[c;r6:4][c;r6:3]-[Nh2:2] >> [n:5]1[c:4][c:3][nH:2][c:1](-[#6:6])1), (F(229),), O=C(COC(=O)[C@H]1CCCN(C(=O)c2ccc(N[C@@H](CS)c3nc

[A0(61), A0(327), A0(267), A0(259), A0(29), A0(155), A0(55), A0(266), A0(26), A0(389), A0(345), A0(57), A0(76), A0(365), A0(101), A0(121), A0(281), A0(287), A0(112), A0(20), A0(321), A0(198), A0(212), A0(124), A0(220), A0(339), A0(135), A0(28), A0(363), A0(356), A0(97), A0(312), A0(21), A0(90), A0(12), A0(174), A0(78), A0(97), A0(298), A0(44), A0(42), A0(280), A0(255), A0(324), A0(250), A0(55), A0(117), A0(345), A0(271), A0(242), A0(379), A0(417), A0(49), A0(68), A0(27), A0(34), A0(371), A0(320), A0(365), A0(105), A0(117), A0(46), A0(58), A0(195)]


In [75]:
probs_1, indices_1 = torch.load('../action_indices_1.pt')
probs_2, indices_2 = torch.load('../action_indices_2.pt')

In [76]:
torch.allclose(probs_1, probs_2)

True

In [77]:
len(indices_1)

60

In [78]:
actions_1 = torch.load('../actions_1.pt')
actions_2 = torch.load('../actions_2.pt')

In [79]:
actions_1

[A0(327), A0(57), A0(12), A0(379)]

In [80]:
actions_2

[A0(327), A0(57), A0(12), A0(379)]

In [81]:
class A0:
    def __init__(self, a):
        self.a = a
    def __eq__(self, other):
        return self.a == other.a
x = [A0(61), A0(327), A0(267), A0(259), A0(29), A0(155), A0(55), A0(266), A0(26), A0(389), A0(345), A0(57), A0(76), A0(365), A0(101), A0(121), A0(281), A0(287), A0(112), A0(20), A0(321), A0(198), A0(212), A0(124), A0(220), A0(339), A0(135), A0(28), A0(363), A0(356), A0(97), A0(312), A0(21), A0(90), A0(12), A0(174), A0(78), A0(97), A0(298), A0(44), A0(42), A0(280), A0(255), A0(324), A0(250), A0(55), A0(117), A0(345), A0(271), A0(242), A0(379), A0(417), A0(49), A0(68), A0(27), A0(34), A0(371), A0(320), A0(365), A0(105), A0(117), A0(46), A0(58), A0(195)]

y = [A0(61), A0(327), A0(267), A0(259), A0(29), A0(155), A0(55), A0(266), A0(26), A0(389), A0(345), A0(57), A0(76), A0(365), A0(101), A0(121), A0(281), A0(287), A0(112), A0(20), A0(321), A0(198), A0(212), A0(124), A0(220), A0(339), A0(135), A0(28), A0(363), A0(356), A0(97), A0(312), A0(21), A0(90), A0(12), A0(174), A0(78), A0(97), A0(298), A0(44), A0(42), A0(280), A0(255), A0(324), A0(250), A0(55), A0(117), A0(345), A0(271), A0(242), A0(379), A0(417), A0(49), A0(68), A0(27), A0(34), A0(371), A0(320), A0(365), A0(105), A0(117), A0(46), A0(58), A0(195)]

x == y

True